# Generated by Django 3.0.2 on 2020-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkki', models.CharField(max_length=100)),
                ('hinta', models.IntegerField()),
            ],
        ),
    ]
